<?php
error_reporting(E_ALL);
include('includes/connection.php');

/*mysql_query("CREATE TABLE webitems (
	item_id INT(11), 
	Code VARCHAR(30), 
	Description VARCHAR(128), 
	InternalCode VARCHAR(30), 
	InternalDesc VARCHAR(128), 
	RetailPricePce FLOAT(5), 
	RetailPriceM2 FLOAT(5), 
	TradePricePce FLOAT(5), 
	TradePriceM2 FLOAT(5), 
	WSaleLoosePricePce FLOAT(5), 
	WSaleLoosePriceM2 FLOAT(5), 
	WSalePalletPricePce FLOAT(5), 
	WSalePalletPriceM2 FLOAT(5), 
	WebPricePce FLOAT(5), 
	WebPriceM2 FLOAT(5), 
	images TEXT, 
	LeadTime FLOAT(5), 
	Weight FLOAT(5), 
	Unit VARCHAR(30), 
	PEIRating VARCHAR(30), 
	SlipRating VARCHAR(30), 
	QtyOnHand INT(6), 
	QtyBackOrdered INT(6), 
	QtyCommitted INT(6), 
	QtyAvailable INT(6), 
	QtyOnOrder INT(6), 
	PcsM2 FLOAT(5), 
	PcsBox FLOAT(5), 
	M2Box FLOAT(5), 
	BoxesPallet FLOAT(5), 
	M2Pallet FLOAT(5), 
	Category VARCHAR(30), 
	CategoryDescription VARCHAR(128), 
	SupplierCode VARCHAR(30), 
	SupplierName VARCHAR(128), 
	SuppStock VARCHAR(128), 
	
	Barcode VARCHAR(128), 
	Type VARCHAR(30), 
	Material VARCHAR(30), 
	Size FLOAT(11), 
	Thickness VARCHAR(30), 
	Use VARCHAR(30), 
	Edge VARCHAR(30), 
	Colour VARCHAR(30), 
	Surface VARCHAR(30), 
	Pattern VARCHAR(30), 
	RelatedTo VARCHAR(30), 
	Heading VARCHAR(128), 
	SubHeading VARCHAR(128), 
	Country VARCHAR(30), 
	Manufacturer VARCHAR(30), 
	Pantone VARCHAR(30), 
	Location VARCHAR(30), 
	Spare VARCHAR(30), 
	WebExport VARCHAR(30), 
	Comment TEXT, 
	Notepad2 TEXT, 
	GstCode VARCHAR(30), 
	GstDesc VARCHAR(30), 
	MinLevel INT(6), 
	MaxLevel INT(6), 
	Comment2 TEXT, 
	
	lastupdate DATETIME,
	is_hidden TINYINT(1), 
	is_active TINYINT(1)
)")
or die(mysql_error());*/

mysql_query("ALTER TABLE webitems 
	ADD COLUMN Barcode VARCHAR(128), 
	ADD COLUMN Type VARCHAR(30), 
	ADD COLUMN Material VARCHAR(30), 
	ADD COLUMN Size FLOAT(11), 
	ADD COLUMN Thickness VARCHAR(30), 
	ADD COLUMN Use VARCHAR(30), 
	ADD COLUMN Edge VARCHAR(30), 
	ADD COLUMN Colour VARCHAR(30), 
	ADD COLUMN Surface VARCHAR(30), 
	ADD COLUMN Pattern VARCHAR(30), 
	ADD COLUMN RelatedTo VARCHAR(30), 
	ADD COLUMN Heading VARCHAR(128), 
	ADD COLUMN SubHeading VARCHAR(128), 
	ADD COLUMN Country VARCHAR(30), 
	ADD COLUMN Manufacturer VARCHAR(30), 
	ADD COLUMN Pantone VARCHAR(30), 
	ADD COLUMN Location VARCHAR(30), 
	ADD COLUMN Spare VARCHAR(30), 
	ADD COLUMN WebExport VARCHAR(30), 
	ADD COLUMN Comment TEXT, 
	ADD COLUMN Notepad2 TEXT, 
	ADD COLUMN GstCode VARCHAR(30), 
	ADD COLUMN GstDesc VARCHAR(30), 
	ADD COLUMN MinLevel INT(6), 
	ADD COLUMN MaxLevel INT(6), 
	ADD COLUMN Comment2 TEXT") 
or die(mysql_error());

?>